### ISSUE TITLE
Animation delay does not seem to work

### ISSUE THREAD

**Issue by ernsheong** [PolymerElements/paper-tooltip#122]
Regardless of what is put in the `animation-delay` attribute (or omitted) there seems to be no delay at all in showing the tooltip in `paper-tooltip` 2.0.1

Anyone else seeing this behavior?

**Comment by djm158** [comment]
Agreed, seems to be an unused property. However, you can do this with CSS custom properties:

```css
:root {
  --paper-tooltip-duration-in: 200ms;
  --paper-tooltip-duration-out: 200ms;
  --paper-tooltip-delay-in: 200ms;
  --paper-tooltip-delay-out: 200ms;
}
```
