### ISSUE TITLE
paper-tooltip.fancy

### ISSUE THREAD

**Issue by gertcuykens** [PolymerElements/paper-tooltip#4]
This doesn't work anymore for me
```css
        paper-tooltip {z-index: 999;}
        paper-tooltip.fancy::shadow .paper-tooltip {
          opacity: 0;
          -webkit-transition: all 300ms cubic-bezier(0,1.92,.99,1.07);
          transition: all 300ms cubic-bezier(0,1.92,.99,1.07);
          -webkit-transform: translate3d(0, -10px, 0);
          transform: translate3d(0, -10px, 0);
        }
        paper-tooltip.fancy:hover::shadow .paper-tooltip,
        paper-tooltip.fancy:focus::shadow .paper-tooltip {
          opacity: 1;
          -webkit-transform: translate3d(0, 0, 0);
          transform: translate3d(0, 0, 0);
        }
```
