### ISSUE TITLE
How to change the `font-size`?

### ISSUE THREAD

**Issue by maxigimenez** [PolymerElements/paper-tooltip#57]
#### Expected outcome
Easily change the `font-size` of the tooltip.

#### Actual outcome
Right now is always `10px`, I try the next snippet and didn't work.

```CSS
paper-tooltip {
  font-size: 14px;
}
```
